#include "mycpu.h"
#include "mycpuinst.h"
#include <stdio.h>

//Adds all the arch register ids to vector
static void VectorAllRegisters(Vector *vector)
{
    for (int i = 0; i < 8; i++)
        vec_push(int, vector, &i);
}

//Moves part of an operand or the whole thing into a register. If the operand is larger than a register, use offset to
//control which part of the operand is loaded.
static void MoveOperandToRegister(MyCpuProgram *program, LinkedList* routineList, IrArchPhysicalLocation *operand, int offsetInBits, uint8_t registerId)
{
    if (operand->physLocationType == IRARCH_PHYS_LOCATION_REGISTER)
    {
        MyCpuInstCCreate(program, routineList, MYCPU_INST_MOV_33, registerId, (uint8_t)operand->registerId, 0);
        return;
    }

    if (operand->physLocationType == IRARCH_PHYS_LOCATION_LITERAL)
    {
        int64_t value = operand->reference.irLiteral.literalValue;
        value >>= offsetInBits;
        int16_t truncValue = (int16_t)value;
        MyCpuInstDCreate(program, routineList, MYCPU_INST_MOV_36, registerId, 0, 0, truncValue, 0);
        return;
    }

    int offsetInBytes = offsetInBits / 8;

    if (operand->physLocationType == IRARCH_PHYS_LOCATION_GLOBAL_MEMORY)
    {
        int effectiveAddress = operand->address + offsetInBytes;
        int bytesToLoad = (operand->reference.size - offsetInBits) / 8;
        if (bytesToLoad < 0)
            bytesToLoad = 0;

        if (bytesToLoad == 0)
        {
            MyCpuInstBCreate(program, routineList, MYCPU_INST_MOV_32, registerId, 0);
            return;
        }

        if (bytesToLoad == 1)
            MyCpuInstDCreate(program, routineList, MYCPU_INST_MOV8_48, 0, registerId, 0, effectiveAddress, 0);
        else
            MyCpuInstDCreate(program, routineList, MYCPU_INST_MOV_40, 0, registerId, 0, effectiveAddress, 0);

        return;
    }

    if (operand->physLocationType == IRARCH_PHYS_LOCATION_STACK)
    {
        int effectiveAddress = operand->address + offsetInBytes;
        int bytesToLoad = (operand->reference.size - offsetInBits) / 8;
        if (bytesToLoad < 0)
            bytesToLoad = 0;

        if (bytesToLoad == 0)
        {
            MyCpuInstBCreate(program, routineList, MYCPU_INST_MOV_32, registerId, 0);
            return;
        }

        if (bytesToLoad == 1)
            MyCpuInstDCreate(program, routineList, MYCPU_INST_MOV8_47, MYCPU_REG_BP, registerId, 0, effectiveAddress, 0);
        else
            MyCpuInstDCreate(program, routineList, MYCPU_INST_MOV_39, MYCPU_REG_BP, registerId, 0, effectiveAddress, 0);

        return;
    }
}

static void MoveRegisterToDestination(MyCpuProgram *program, LinkedList* routineList, IrArchPhysicalLocation *dstOperand, int byteOffset, int srcRegister, int srcSizeBytes)
{
    if (dstOperand->physLocationType == IRARCH_PHYS_LOCATION_REGISTER && srcRegister != dstOperand->registerId)
    {
        MyCpuInstCCreate(program, routineList, MYCPU_INST_MOV_33, dstOperand->registerId, srcRegister, 0);
        return;
    }

    if (dstOperand->physLocationType == IRARCH_PHYS_LOCATION_STACK)
    {
        int effectiveAddress = dstOperand->address + byteOffset;
        if (srcSizeBytes == 1)
            MyCpuInstDCreate(program, routineList, MYCPU_INST_MOV8_45, MYCPU_REG_BP, srcRegister, 0, effectiveAddress, 0);
        else
            MyCpuInstDCreate(program, routineList, MYCPU_INST_MOV_37, MYCPU_REG_BP, srcRegister, 0, effectiveAddress, 0);
        return;
    }

    if (dstOperand->physLocationType == IRARCH_PHYS_LOCATION_GLOBAL_MEMORY)
    {
        int effectiveAddress = dstOperand->address + byteOffset;
        if (srcSizeBytes == 1)
            MyCpuInstDCreate(program, routineList, MYCPU_INST_MOV8_46, 0, srcRegister, 0, effectiveAddress, 0);
        else
            MyCpuInstDCreate(program, routineList, MYCPU_INST_MOV_38, 0, srcRegister, 0, effectiveAddress, 0);
        return;
    }
}

static bool IsImmediatelyAddable(IrLiteral *literal)
{
    if (literal->literalValue <= MYCPU_IMMD_MAX)
        return true;
    if (literal->literalValue >= MYCPU_IMMD_MIN)
        return true;
    return false;
}

//Returns the list machine instructions generated by this routine.
//registerIds: An array of register ids sorted from least to most relevant. Less relevant registers will be clobbered first.
//clobberedRegisters: An out array of registered clobbered by this routine.
static LinkedList AddOptimized(
    MyCpuProgram *program,
    IrArchPhysicalLocation *operands,
    int *registerIds,
    int *clobberedRegisters,
    int *clobberedRegisterCount
)
{
    LinkedList routineList = {0};
    IrArchPhysicalLocation *op0 = &operands[0];
    IrArchPhysicalLocation *op1 = &operands[1];
    IrArchPhysicalLocation *dstOp = &operands[2];
    
    //Prefer the literal to be the right hand size since addition is commutative
    if (op0->reference.type == IRREF_LITERAL)
    {
        IrArchPhysicalLocation *temp = op0;
        op0 = op1;
        op1 = temp;
    }

    int clobberCount = 0;
    int clobberSearchIdx = 0;
    int addResultRegister = 0;

    //We'll add directly into op0's register if it is in a register
    if (op0->physLocationType == IRARCH_PHYS_LOCATION_REGISTER)
        addResultRegister = op0->registerId;
    else
    {
        addResultRegister = registerIds[clobberSearchIdx];

        //Avoid register overlap
        if (addResultRegister == op1->registerId && op1->physLocationType == IRARCH_PHYS_LOCATION_REGISTER)
        {
            clobberSearchIdx++;
            addResultRegister = registerIds[clobberSearchIdx];
        }
        clobberSearchIdx++;
    }

    clobberedRegisters[clobberCount] = addResultRegister;
    clobberCount++;

    //If op1 is already in a register, we shouldn't have to move it and clobber another register
    int addSourceRegister = op1->registerId;
    if (op1->physLocationType == IRARCH_PHYS_LOCATION_STACK ||
        op1->physLocationType == IRARCH_PHYS_LOCATION_GLOBAL_MEMORY ||
        op1->physLocationType == IRARCH_PHYS_LOCATION_LITERAL &&
        !IsImmediatelyAddable(&op1->reference.irLiteral))
    {
        addSourceRegister = registerIds[clobberSearchIdx];
        //Avoid register overlap
        if (addSourceRegister == addResultRegister)
        {
            clobberSearchIdx++;
            addSourceRegister = registerIds[clobberSearchIdx];
            clobberSearchIdx++;
        }
        clobberedRegisters[clobberCount] = addSourceRegister;
        clobberCount++;
    }

    //This architecture's add instruction clobbers the input register, so make that the output register
    if (dstOp->physLocationType == IRARCH_PHYS_LOCATION_REGISTER)
    {
        dstOp->registerId = addResultRegister;
    }

    int sizeInBits = op0->reference.size;
    if (op1->reference.size > sizeInBits)
        sizeInBits = op1->reference.size;
    int sizeInBytes = sizeInBits / 8;

    //Notes: Even if the operands are different widths, you still must add the leading zeros due to possible carries
    for (int bitOffset = 0, byteOffset = 0; bitOffset < sizeInBits; bitOffset += 16, byteOffset += 2)
    {
        //Move the first operand into position, unless it is already there
        if (bitOffset != 0 || op0->physLocationType != IRARCH_PHYS_LOCATION_REGISTER)
        {
            MoveOperandToRegister(program, &routineList, op0, bitOffset, addResultRegister);
        }

        //We can do the add in an immediate fashion
        if (bitOffset == 0 && op1->physLocationType == IRARCH_PHYS_LOCATION_LITERAL && IsImmediatelyAddable(&op1->reference.irLiteral))
        {
            MyCpuInstDCreate(program, &routineList, MYCPU_INST_ADD_6, addResultRegister, 0, 0, (int16_t)op1->reference.irLiteral.literalValue, 0);
            MoveRegisterToDestination(program, &routineList, dstOp, byteOffset, addResultRegister, sizeInBytes - byteOffset);
            continue;
        }

        //Move the second operand into position, unless it is already there
        if (bitOffset != 0 || op1->physLocationType != IRARCH_PHYS_LOCATION_REGISTER)
        {
            MoveOperandToRegister(program, &routineList, op1, bitOffset, addSourceRegister);
        }

        if (bitOffset == 0)
            MyCpuInstCCreate(program, &routineList, MYCPU_INST_ADD_5, addResultRegister, addSourceRegister, 0);
        else
            MyCpuInstCCreate(program, &routineList, MYCPU_INST_ADC_2, addResultRegister, addSourceRegister, 0);

        MoveRegisterToDestination(program, &routineList, dstOp, byteOffset, addResultRegister, sizeInBytes - byteOffset);
    }

    *clobberedRegisterCount = clobberCount;
    return routineList;
}

//Returns whether the destination operand should be allocated in memory or may be a register
static void GetAddRequirements(IrReference *operands, IrArchValueLocationRequirement *dstRequirment)
{
    if (operands[0].size > 16 || operands[1].size > 16)
    {
        dstRequirment->requiredLocation = IRARCH_LOCATION_MEMORY;
    }
    else
    {
        dstRequirment->requiredLocation = IRARCH_LOCATION_REGISTER;
        VectorAllRegisters(&dstRequirment->validRegisterIds);
    }
}

void IrArchMyCpuInit(IrArch *arch)
{
    MyCpuProgram *program = malloc(sizeof(MyCpuProgram));
    MyCpuProgramInit(program);

    *arch = (IrArch)
    {
        .registers = vec_new(IrArchRegister, 8),
        .pointerSize = 16,
        .program = program,
        .addCallback = AddOptimized,
        .addDstRequirementsCallback = GetAddRequirements
    };

    for (int i = 0; i < 8; i++)
    {
        IrArchRegister reg = (IrArchRegister)
        {
            .registerId = i,
            .size = 16
        };
        vec_push(IrArchRegister, &arch->registers, &reg);
    }

}

void IrArchMyCpuDestroy(IrArch *arch)
{
    MyCpuProgramDestroy(arch->program);
    vec_free(&arch->registers);
}